spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: ${DB_HOMOLOG_USERNAME}
    password: ${DB_HOMOLOG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
