server:
  port: 80
spring:
  thymeleaf:
    check-template-location: false
  profiles:
    active: homologacao
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  # Development properties (also used for docker-compose)
  config:
    import: optional:file:.env[.properties]
site:
  id: 1

